In [1]:
import matplotlib.pyplot as plot
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

from sklearn.utils import shuffle

Using TensorFlow backend.


In [2]:
# 학습에 필요한 데이터 정리
M = 2
K = 3
n = 100
N = n * K

In [3]:
# 샘플 데이터
X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])

Y1 = np.array([[1, 0, 0] for i in range(n)])
Y2 = np.array([[0, 1, 0] for i in range(n)])
Y3 = np.array([[0, 0, 1] for i in range(n)])

X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)

In [4]:
# 모델 정의
model = Sequential([
    Dense(input_dim=M, units=K),
    Activation('softmax')
])
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))

In [5]:
# 미니 배치의 크기
minibatch_size = 50

In [6]:
# 학습
model.fit(X, Y, epochs=20, batch_size=minibatch_size)

Epoch 1/20
300/300 [==============================] - 0s 485us/step - loss: 4.3952
Epoch 2/20
300/300 [==============================] - 0s 48us/step - loss: 0.1692
Epoch 3/20
300/300 [==============================] - 0s 100us/step - loss: 0.1053
Epoch 4/20
300/300 [==============================] - 0s 140us/step - loss: 0.0797
Epoch 5/20
300/300 [==============================] - 0s 101us/step - loss: 0.0676
Epoch 6/20
300/300 [==============================] - 0s 78us/step - loss: 0.0597
Epoch 7/20
300/300 [==============================] - 0s 70us/step - loss: 0.0537
Epoch 8/20
300/300 [==============================] - 0s 63us/step - loss: 0.0499
Epoch 9/20
300/300 [==============================] - 0s 76us/step - loss: 0.0468
Epoch 10/20
300/300 [==============================] - 0s 72us/step - loss: 0.0437
Epoch 11/20
300/300 [==============================] - 0s 101us/step - loss: 0.0418
Epoch 12/20
300/300 [==============================] - 0s 56us/step - loss: 0.0394
Epoch 13

In [7]:
# 분류가 잘 되었는지 테스트
X_, Y_ = shuffle(X, Y)
classes = model.predict_classes(X_[0:10], batch_size=minibatch_size)
prob = model.predict_proba(X_[0:10], batch_size=minibatch_size)

In [8]:
print('classified:')
print(np.argmax(model.predict(X_[0:10]), axis=1) == classes)

classified:
[ True  True  True  True  True  True  True  True  True  True]


In [9]:
print('prob:')
print(prob)

prob:
[[9.8865509e-01 1.1344897e-02 1.2537251e-09]
 [9.9833626e-01 1.6637840e-03 1.7805871e-10]
 [7.6950748e-09 1.2087158e-02 9.8791283e-01]
 [8.4641855e-10 6.9245044e-03 9.9307549e-01]
 [9.6260822e-01 3.7391674e-02 1.2131213e-07]
 [7.7679157e-02 9.1886270e-01 3.4582464e-03]
 [2.2107007e-09 8.0751264e-03 9.9192482e-01]
 [9.9896395e-01 1.0360912e-03 5.1581919e-11]
 [1.5374191e-02 9.8444760e-01 1.7810713e-04]
 [2.0533945e-02 9.7690821e-01 2.5579012e-03]]
